// MIRADOR — P-043 THE EXCHANGE LEDGER (prompt-4 R7 · E58): frozen byte
// baselines + the 7 mandatory cells + the ΣΔ≤0 arithmetic. Generates
// docs/exchange-ledger.md from LIVE measurements (fonts) + the frozen
// baselines + the prod-run raw files when present; build-dependent cells
// carry their run-11 baseline and re-assert at the exit gate (E79).
// Re-run: bun scripts/exchange-ledger.ts  (docs regenerate, never hand-edit)
import { statSync, readdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const FONTS = "public/fonts";

// — FROZEN baselines (prompt-4 §5 notes + run-11 raw = the release's basis) —
const BASE = {
  fontDisk: 334_880, // §5 cell ⑥ baseline (pre-R9)
  firstLoadMax: 180_900, // run-11 raw max route (/menu 176.7KB… private-dining 232.4KB was the breach)
  firstLoadBreach: 237_940, // run-11 /private-dining (pre-zod-fix)
  motionFamily: 57_540, // run-11 marker chunks (56.2KB)
  threePack: 235_263, // run-11 (229.7KB)
  combinedRental: 291_150, // §5 note (291.15KB)
  cssSubscribed: 2_970, // §5: ≈2.97KB of the +3KB ceiling subscribed at contract open
};

// — live measurements —
let fontDisk = 0;
for (const f of readdirSync(FONTS)) fontDisk += statSync(join(FONTS, f)).size;

const table = "evidence/F12-2/prod-run/first-load-js-gz.txt";
let firstLoadMax: number | null = null;
let breaches: string[] = [];
if (existsSync(table)) {
  for (const line of readFileSync(table, "utf8").split("\n")) {
    const m = line.match(/^(\/\S+) — files=\d+ raw=\d+B gz=(\d+)B/);
    if (!m) continue;
    const gz = Number(m[2]);
    if (gz > 200_000) breaches.push(`${m[1]} ${(gz / 1024).toFixed(1)}KB`);
    firstLoadMax = Math.max(firstLoadMax ?? 0, gz);
  }
}

const manifest = "evidence/F12-2/prod-run/chunk-manifest.txt";
let motionFamily: number | null = null;
if (existsSync(manifest)) {
  motionFamily = 0;
  for (const line of readFileSync(manifest, "utf8").split("\n")) {
    if (!/refs=0 \(lazy/.test(line)) continue;
    if (/markers=\[(ScrollTrigger|Flip|lenis)/.test(line)) {
      const m = line.match(/gz=(\d+)B/);
      if (m) motionFamily! += Number(m[1]);
    }
  }
}

const threeFile = "evidence/F6-3/prod-run/three-lazy-chunk.txt";
let threePack: number | null = null;
if (existsSync(threeFile)) {
  const m = readFileSync(threeFile, "utf8").match(/pack total: raw=\d+B gz=(\d+)B/);
  if (m) threePack = Number(m[1]);
}

// — the 7 cells + ΣΔ≤0 arithmetic —
const Δfonts = fontDisk - BASE.fontDisk; // negative = bytes removed from disk
const ΔfirstLoad = firstLoadMax !== null ? firstLoadMax - BASE.firstLoadBreach : null; // vs the run-11 breach route
const Δmotion = motionFamily !== null ? motionFamily - BASE.motionFamily : null;
const Δthree = threePack !== null ? threePack - BASE.threePack : null;

const fmt = (n: number | null) => (n === null ? "exit-gate" : `${(n / 1024).toFixed(1)}KB`);
const fmtB = (n: number | null) => (n === null ? "exit-gate" : `${n >= 0 ? "+" : ""}${n}B`);

const lines: string[] = [];
lines.push("# THE EXCHANGE LEDGER (P-043, prompt-4 R7 · E58) — machine-generated " + new Date().toISOString());
lines.push("");
lines.push("The 7 mandatory cells + the ΣΔ≤0 arithmetic. Generated by `scripts/exchange-ledger.ts` —");
lines.push("regenerates from live disk + the prod-run raw files; build-dependent cells re-assert at the");
lines.push("exit gate (E79) after R8–R11 land. Basis: prompt-4 §5 frozen baselines + run-11 raw.");
lines.push("");
lines.push("| # | Cell | Ceiling | Baseline (run-11 / §5) | Current | Δ |");
lines.push("|---|---|---|---|---|---|");
lines.push(`| ① | first-load JS (max route, gz) | ≤200KB hard · 165KB soft (gates R2) | 232.4KB (private-dining, PRE-zod-fix breach) | ${fmt(firstLoadMax)}${breaches.length ? ` ⚠ ${breaches.join(", ")} over hard cap` : " (0 breaches)"} | ${fmtB(ΔfirstLoad)} |`);
lines.push(`| ② | motion family (lazy, gz) | ≤62KB | 56.2KB | ${fmt(motionFamily)} | ${fmtB(Δmotion)} |`);
lines.push(`| ③ | three-pack (lazy, gz) | ≤235KB | 229.7KB | ${fmt(threePack)} | ${fmtB(Δthree)} |`);
lines.push(`| ④ | combined rental (motion+three, gz) | ≤297KB | 291.15KB (§5 note) | ${motionFamily !== null && threePack !== null ? fmt(motionFamily + threePack) : "exit-gate"} | — |`);
lines.push(`| ⑤ | CSS additions | +3KB total | ≈2.97KB subscribed | exit-gate (compiled CSS measured on the Actions build) | — |`);
lines.push(`| ⑥ | fonts (AR faces ≤60KB each; disk) | disk 334,880B baseline | 334,880B | ${fontDisk}B | ${fmtB(Δfonts)} |`);
lines.push("");
lines.push("## ΣΔ≤0 arithmetic (bytes removed vs added, this release)");
lines.push("");
lines.push("```");
lines.push(`fonts (disk):        ${Δfonts}B   (R9 wordmark/corpus subsets + R9a — REMOVED)`);
if (ΔfirstLoad !== null) lines.push(`first-load (wire):   ${ΔfirstLoad}B   (run-11 breach route − zod-off-the-wire fix [this release] — measured at the exit gate)`);
else lines.push(`first-load (wire):   exit-gate (run-11 recorded the private-dining 232.4KB breach; the zod fix removes the 63,952B chunk — re-measured at E79)`);
if (Δmotion !== null) lines.push(`motion family (lazy): ${Δmotion}B`);
if (Δthree !== null) lines.push(`three-pack (lazy):   ${Δthree}B`);
lines.push(`CSS:                  +~1.2KB source (P-082 fallback faces) — counts against the +3KB ceiling (cell ⑤), not the net-wire Σ`);
lines.push("```");
lines.push("");
lines.push("The wire Σ (①+②+③+⑥ deltas) must land ≤ 0 at the exit gate; fonts alone are −35,560B.");
lines.push("Cell ⑤ has its own +3KB ceiling. A failing threshold ships as FAIL (N16/N24) — never polished.");
lines.push("");

writeFileSync("docs/exchange-ledger.md", lines.join("\n") + "\n");
console.log(lines.join("\n"));
console.log("\n→ docs/exchange-ledger.md");
